### ISSUE TITLE
Cook point menu was parsed when it was closed

### ISSUE THREAD

**Issue by kasicka** [oskutka/rhlp#38]
On 7th May (Monday before public holiday), Cook point was closed, but the menu was parsed.
I understand that the fault is partially on the Cook point's side, because they have published daily menu on their site, but in the [pdf](http://www.cookpoint.cz/files/1062_menu.pdf), it is stated that the restaurant is closed.

**Comment by oskutka** [comment]
I'm sorry for the inconvenience it caused to you (and actually to me as well). 

In terms of how to prevent this from happening in the future, I'm not sure whether parsing just the pdf is a better approach. From my experience, restaurants are more likely to update their daily (html) menu than the weekly (pdf) one. In other words - html tends to be the more correct one.

I guess the most precise approach would be to parse both html and pdf and compare them, notifying the user if there's a mismatch. But that would be too complicated a solution (but you're welcome to submit a patch ;-) ).

Anyway, I suggest contacting Cook Point and asking them to have correct information on their pages.

Thanks for submitting the issue, however since (I hope) this is a one-off, I'll close it now.
